script:
  - mkdir build
  - cd build
  - cmake ${CMAKEFLAGS} -DCMAKE_CXX_COMPILER=${CXX} -DCMAKE_C_COMPILER=${CC} ..
  - make
  - make test

sudo: required
dist: trusty

matrix:
  include:
    - compiler: gcc
      os: osx
      before_script:
        - brew update
        - brew outdated cmake || brew upgrade cmake
      env: CXX=g++
    - compiler: clang
      os: osx
      before_script:
        - brew update
        - brew outdated cmake || brew upgrade cmake
      env: CXX=clang++
    - compiler: gcc
      os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
            - cmake
      env: CXX=g++-4.9
    - compiler: gcc
      os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
            - cmake
      env: CXX=g++-5
    - compiler: gcc
      os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
            - cmake
      env: CXX=g++-6
    - compiler: clang
      os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6
          packages:
            - clang-3.6
            - cmake
      env: CXX=clang++-3.6
    - compiler: clang
      os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.7
          packages:
            - clang-3.7
            - cmake
      env: CXX=clang++-3.7

env:
  global:
    # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
    #   via the "travis encrypt" command using the project repo's public key
    - secure: "Jt0baUgI9mwbUptf+4NpYJREp7s2YfDj+jH7e9ZTAdriuN6h8Qwtd+tHjIusAG5iO4wecHOh8kOxlDvqTAn6YiXnHELhJieNxFIFwUlyfwYpnNMF41JpO5nsvyffu/xSJHw1hUpJ5xJDOKOBAQ1UBR42gM56hJfyjRE8zoKxM0s="

addons:
  coverity_scan:
    project:
      name: "dascandy/hippomocks"
      description: "HippoMocks, C++11 Mocking Framework"
      notification_email: dascandy@gmail.com
      build_command: make && make test
      branch_pattern: master

