version: 1.0.{build}

clone_folder: C:\dev\hippomocks

build_script:
  - cd C:\dev\hippomocks 
  - md build12
  - cd build12
  - cmake -G"Visual Studio 12" ..
  - msbuild /m /p:Configuration=Debug /p:Platform=Win32 hippomocks.sln
  - ctest -C Debug -VV
  - cd C:\dev\hippomocks 
  - md build14
  - cd build14
  - cmake -G"Visual Studio 14" ..
  - msbuild /m /p:Configuration=Debug /p:Platform=Win32 hippomocks.sln
  - ctest -C Debug -VV
  - cd C:\dev\hippomocks 
  - md build12_64
  - cd build12_64
  - cmake -G"Visual Studio 12 Win64" ..
  - msbuild /m /p:Configuration=Debug /p:Platform=x64 hippomocks.sln
  - ctest -C Debug -VV
  - cd C:\dev\hippomocks 
  - md build14_64
  - cd build14_64
  - cmake -G"Visual Studio 14 Win64" ..
  - msbuild /m /p:Configuration=Debug /p:Platform=x64 hippomocks.sln
  - ctest -C Debug -VV

platform:
  - Win32

configuration:
  - Debug

matrix:
  fast_finish: true
